#spring.application.name=gateway
#server.port=8080
#eureka.client.region=default
#eureka.client.registryFetchIntervalSeconds=5
#
#management.security.sessions=always
#
#zuul.routes.firm.path=/firm_service/**
#zuul.routes.firm.sensitive-headers=Set-Cookie,Authorization
#hystrix.command.firm.execution.isolation.thread.timeoutInMilliseconds=600000
#
#zuul.routes.tank.path=/tank_service/**
#zuul.routes.tank.path=/amun.jsf
#zuul.routes.tank.sensitive-headers=Set-Cookie,Authorization
#hystrix.command.tank_service.execution.isolation.thread.timeoutInMilliseconds=600000
#
#zuul.routes.human.path=/human_service/**
#zuul.routes.human.sensitive-headers=Set-Cookie,Authorization
#hystrix.command.human_service.execution.isolation.thread.timeoutInMilliseconds=600000
#
#zuul.routes.discovery.path=/discovery/**
#zuul.routes.discovery.sensitive-headers=Set-Cookie,Authorization
#zuul.routes.discovery.url=http://localhost:8082
#hystrix.command.discovery.execution.isolation.threadi.timeoutInMilliseconds=600000
#
#spring.redis.host=localhost
#spring.redis.port=6379

spring:
  application:
    name: gateway

zuul:
  routes:
    firm:
      path: /firms/**
      serviceId: firm
      strip-prefix: false

server:
  port: 8080

